### ISSUE TITLE
Psalm, code static analiysis, + Sarif report

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/gh-actions-yaml-generator#111]
In code quality section, for Psalm Code static analysis tool, add checkbox to create and upoad Sarif report
- [x] add --report=result.sarif
```
      - name: Execute Code Static Analysis (PSALM)
        run: |
          vendor/bin/psalm --report=result.sarif
```
- [x] upload result.sarif
```
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: result.sarif
```
