### ISSUE TITLE
Add Laravel Matrix

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/gh-actions-yaml-generator#19]
Add Laravel Matrix in order to use some specific version of Laravel.
Follow this great article to understand the right directive to use for use the Matrix : 
https://freek.dev/1546-using-github-actions-to-run-the-tests-of-laravel-projects-and-packages
Step to implement:
- [x] Add Laravel versions in to matrix (8.*, 7.* and 6.*)
- [x] Add dependencies for selected laravel version (orchestra/testbench)

```
        laravel: [8.*, 7.* ]
        include:
            - laravel: 8.*
              testbench: 6.*
            - laravel: 7.*
              testbench: 5.*
```
- [x] set the name that reflect the previous selection:
```
name: P${{ matrix.php-versions }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.operating-system}}
```
- [x] __if the user selected_ some specific version of Laravel_ install dependencies via require/update instead of _composer install_:
```
    - name: Install Laravel Dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
        composer update --${{ matrix.dependency-stability }} --prefer-dist --no-interaction --no-suggest
