### ISSUE TITLE
Error generating YAML

### ISSUE THREAD

**Issue by Braunson** [Hi-Folks/gh-actions-yaml-generator#75]
Using the latest version, tried generating a YAML file..

```
Error
Reference "" does not exist at line 1 (near "- *").
There was some error during validation. Take a look about your data in the form:
Reference "" does not exist at line 1 (near "- *").
```

Renders out this YAML file:

```yaml
name: Template - Laravel application (Mysql)
on:
  push:
    branches:
      - master
      - staging
      - testing
      - production
      - develop
      - features/**
      - updates/**
      - update/**
      - fix/**
      - patch/**
  pull_request:
    branches:
      - *
 
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
# Service container Mysql mysql
    services:
      # Label used to access the service container
      mysql:
        # Docker Hub image (also with version)
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE:  homestead
        ## map the "external" 33306 port with the "internal" 3306
        ports:
          - 33306:3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
 
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: [ '8.0','7.4' ]
        dependency-stability: [ prefer-stable ]
 
    name: P${{ matrix.php-versions }} - L${{ matrix.laravel }} - ${{ matrix.dependency-stability }} - ${{ matrix.operating-system}}
 
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Cache node_modules directory
      uses: actions/cache@v2
      id: node_modules-cache
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install NPM packages
      if: steps.node_modules-cache.outputs.cache-hit != 'true'
      run: npm ci
    - name: Build frontend
      run: npm run development
    - name: Install PHP versions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    - name: Get Composer Cache Directory 2
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
     - uses: actions/cache@v2
      id: actions-cache
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
     - name: Cache PHP dependencies
      uses: actions/cache@v2
      id: vendor-cache
      with:
        path: vendor
        key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      if: steps.vendor-cache.outputs.cache-hit != 'true'
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
 
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Run Migrations
# Set environment
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: homestead
        DB_PORT: 33306
        DB_USER: root
        DB_PASSWORD: secret
 
      run: php artisan migrate
 
    - name: Show dir
      run: pwd
    - name: PHP Version
      run: php --version
 
# Code quality
    - name: Execute tests (Unit and Feature tests) via PHPUnit
# Set environment
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: homestead
        DB_PORT: 33306
        DB_USER: root
        DB_PASSWORD: secret
 
      run: vendor/bin/phpunit --testdox
 
    - name: Execute Code Sniffer via phpcs
      run: |
        composer require --dev squizlabs/php_codesniffer
        vendor/bin/phpcs --standard=PSR12 app
 
    - name: Execute Code Static Analysis (PHP Stan + Larastan)
      run: |
        composer require --dev nunomaduro/larastan
        vendor/bin/phpstan analyse app -c ./vendor/nunomaduro/larastan/extension.neon  --level=4 --no-progress
 
 
 
 
    - name: Browser Test - upgrade and start Chrome Driver
      run: |
        composer require --dev laravel/dusk
        php artisan dusk:chrome-driver --detect
        ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &
     - name: Run Dusk Tests
      run: |
        php artisan serve > /dev/null 2>&1 &
        chmod -R 0755 vendor/laravel/dusk/bin/
        php artisan migrate
        php artisan dusk
 # Set environment
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: homestead
        DB_PORT: 33306
        DB_USER: root
        DB_PASSWORD: secret
```
