### ISSUE TITLE
Indentation problem at line 10 (near " pull_request:").

### ISSUE THREAD

**Issue by Braunson** [Hi-Folks/gh-actions-yaml-generator#8]
Getting this error generating the YAML file.

### Info
- Using latest copy of this repo
- Running on PHP 7.4.11
- Running on Windows 10 

### Error on generation

> Indentation problem at line 10 (near " pull_request:").

### Settings

- [x] On Push
	`master,develop,fix/**,fixes/**,features/**`
- [x] On Pull Request
	`master`
- [x] MySQL Service
    - Version: 5.7
    - Database Name: `homestead`
    - Database Port: 33306
- [x] Cache PHP Packages
- [x] Cache Vendor Directory
- [x] Cache NPM Modules
- Environments
    - [x] 8.0
    - [x] 7.4
 - Run Migrations
 - Fix Storage Permissions
 - Execute Code Sniffer with phpcs

### Generated YAML with the error

```yaml
name: Test Laravel Github action
on:
  push:
    branches:
          - master
          - develop
          - fix/**
          - fixes/**
          - features/**
      pull_request:
    branches:
          - master
    
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
# Service container Mysql mysql
    services:
      # Label used to access the service container
      mysql:
        # Docker Hub image (also with version)
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE:  homestead
        ## map the "external" 33306 port with the "internal" 3306
        ports:
          - 33306:3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: [ '8.0','7.4' ]
    steps:
    - uses: actions/checkout@v2
    - name: Install PHP versions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    - name: Get Composer Cache Directory 2
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v2
      id: actions-cache
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: Cache PHP dependencies
      uses: actions/cache@v2
      id: vendor-cache
      with:
        path: vendor
        key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      if: steps.vendor-cache.outputs.cache-hit != 'true'
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Run Migrations
# Set environment
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: homestead
        DB_PORT: 33306
        DB_USER: root

      run: php artisan migrate
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
# Set environment
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: homestead
        DB_PORT: 33306
        DB_USER: root

      run: vendor/bin/phpunit --testdox

    - name: Execute Code Sniffer via phpcs
      run: |
        composer require --dev squizlabs/php_codesniffer
        vendor/bin/phpcs --standard=PSR12 app
```
