### ISSUE TITLE
Add Vapor Deploy

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/gh-actions-yaml-generator#82]
Today we have Ploi integration for Deploy Laravel application.
Following this instructions:
https://docs.vapor.build/1.0/projects/deployments.html#deploying-from-ci
Add deploy to Vapor fuctionality:
```yaml
      - name: Require Vapor CLI
        run: composer global require laravel/vapor-cli
      - name: Deploy Environment
        run: vapor deploy
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
```
Parameter: API token "from secret"

<img width="1203" alt="Screenshot 2021-06-11 at 19 17 47" src="https://user-images.githubusercontent.com/678434/121725619-ca96c000-cae9-11eb-8bca-a2299d85e838.png">
