### ISSUE TITLE
Add a job in GitHub Actions workflow for Security Check

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/gh-actions-yaml-generator#94]
Using the actions https://github.com/marketplace/actions/the-php-security-checker , add a job in theGithHub Actions workflow for executing security check.
- executing on every push
```yaml
on:
  push:
    branches:
      - main
      - develop
      - features/**
```
- scheduling at 7:30 am and 5:30pm
```yaml
on:
  schedule:
    - cron:  '30 7,17 * * *'
 ```
- steps are: checkout and using the security check action:
```yaml
steps:
    - uses: actions/checkout@v2
    - uses: symfonycorp/security-checker-action@v2
 ```
